---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitops-demo-secret
  namespace: gitops-demo
spec:
  encryptedData:
    DEMO_API_KEY: AgATiddVXc1KMYVz6PyFLrF0SFC8MnMqQjWqhkTR9PwuDIaMaI2w7T9PAa/5PiQMjZqdOQCgKpCJQ6abZQGfq6MfrGEuOPnQcHKHoOiTwGQdYurUhOmzAdu0kIcZzkqhnmDQc20F3by/Wf+X/0b5uz9hUx82ptsPFGKbUUvMXq65rbIvC5gQU2nY/ulPtPLelEr8ps05CSJ8XL6MzhxYMwwDq6RPTA9OlvIpJVbIJYRHGlvunFmxNSfGf9JzXeYPfKL5AbBNAxhW+8mUItICYP6imZd/VyoYpwju8fDucFVa58E7MMP9bKCzV7rN2h7bk+/rH9wAEb4l9x550836r7Xe8/PzWtvLEPCRx5E+Uo+0Zim3SeVwfySn9AjksxNVqcOKJOgVvg0/cnL/DJ6DrSoYeHdebB6ErBP+Yay3iqwg8mtOZsgT7sLPkALgc1JsSG6CtZvt6ZpwV7kxcHEIoBXkTAa2LK2uRYi+0gMNMKx6TKmLDG5f4EViUTXEdWqFFbD1ctJtTgYCR4gu0HcqSHen9Tabc2t2zwyyl+S6DkvGDPwCMEbGfeQQO5CN6gvkt2cPypnFmr/i5OSp6oTH57EEX2776AySzrUd95cjkNNxkTIMc4mf4OLYhtjACYxbmWUuAcXUt0ITA7idp3cOgkJSJmetHvg97EIEtBzcWcuitQFNaORoZKm3V9n+kfQqFGO3ggaKm7yBPiMcL8QsfrFS1YYkjpuAGA==
  template:
    metadata:
      name: gitops-demo-secret
      namespace: gitops-demo
