apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-demo.fullname" . }}
  labels:
    {{- include "gitops-demo.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "gitops-demo.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
